//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.AllotedRooms = new HashSet<AllotedRoom>();
            this.CourseAssigns = new HashSet<CourseAssign>();
            this.Results = new HashSet<Result>();
            this.StudentEnrolledCourses = new HashSet<StudentEnrolledCourse>();
        }
    
        public int courseId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<double> CourseCredit { get; set; }
        public string CourseDescription { get; set; }
        public string depCode { get; set; }
        public Nullable<int> SemesterID { get; set; }
    
        public virtual ICollection<AllotedRoom> AllotedRooms { get; set; }
        public virtual Department Department { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual ICollection<CourseAssign> CourseAssigns { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<StudentEnrolledCourse> StudentEnrolledCourses { get; set; }
    }
}
