//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int gradeID { get; set; }
        public string gradeLetter { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
    }
}
