//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Results = new HashSet<Result>();
            this.StudentEnrolledCourses = new HashSet<StudentEnrolledCourse>();
        }
    
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentEmail { get; set; }
        public Nullable<long> studentContactNo { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
        public string studentAddress { get; set; }
        public string depCode { get; set; }
        public string CurrentYear { get; set; }
        public string RegistrationNo { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<StudentEnrolledCourse> StudentEnrolledCourses { get; set; }
    }
}
