//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AllotedRooms = new HashSet<AllotedRoom>();
            this.Courses = new HashSet<Course>();
            this.CourseAssigns = new HashSet<CourseAssign>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public string depCode { get; set; }
        public string depName { get; set; }
    
        public virtual ICollection<AllotedRoom> AllotedRooms { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CourseAssign> CourseAssigns { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
